Changing log statements based on new logging implementation
Tendrl/ceph_integration pull request #103
Opened 2017-02-01 09:01 UTC by GowthamShanmugam

tendrl-bug-id: Tendrl/specifications#28
tendrl-spec:logging_change

Signed-off-by: root <root@dhcp42-75.lab.eng.blr.redhat.com>

2017-02-01 09:02 UTC, GowthamShanmugam commented
@brainfunked @shtripat @anmolbabu @nnDarshan @r0h4n @nthomas-redhat @anmolsachan please review this

2017-02-01 09:07 UTC, GowthamShanmugam commented on tendrl/ceph_integration/manager/crud.py
> -                    return rc
@brainfunked @shtripat @anmolbabu @nnDarshan @r0h4n @nthomas-redhat LOG.exception, i gave warning priority for this is that ok?

2017-02-01 16:30 UTC, r0h4n requested changes

2017-02-01 16:30 UTC, r0h4n commented on tendrl/ceph_integration/manager/__init__.py
> +            print(traceback.format_exc())
this should be logged instead of print

2017-02-01 16:30 UTC, r0h4n commented on tendrl/ceph_integration/manager/crud.py
> +                        print(traceback.format_exc())
log instead of print

2017-02-01 16:30 UTC, r0h4n commented on tendrl/ceph_integration/manager/__init__.py
> +        try:
abstract out this try/except block. This seems to have been copied in the entire PR, please abstract it

2017-02-02 09:19 UTC, GowthamShanmugam commented on tendrl/ceph_integration/manager/__init__.py
> +            print(traceback.format_exc())
@r0h4n This will give error when socket failed, if socket failed we cant log anything, so we cant log it

2017-02-02 09:19 UTC, GowthamShanmugam commented on tendrl/ceph_integration/manager/crud.py
> +                        print(traceback.format_exc())
@r0h4n This will give error when socket failed, if socket failed we cant log anything, so we cant log it

2017-02-15 00:35 UTC, cybernth requested changes

2017-02-15 00:35 UTC, nthomas-redhat commented on tendrl/ceph_integration/manager/crud.py
> +                        print(traceback.format_exc())
@GowthamShanmugam @anmolsachan , This is ugly. Don't throw back the exceptions from Event, handle it(pushing to stderr) there itself. Handling this all over the code make our life tough

2017-02-15 06:09 UTC, GowthamShanmugam commented
@anmolsachan please this PR as per new change

2017-02-20 08:09 UTC, closed without merging