Datetime function is moved to commons
Tendrl/ceph_integration pull request #105
Opened 2017-02-02 13:48 UTC by GowthamShanmugam

Signed-off-by: root <root@dhcp42-75.lab.eng.blr.redhat.com>

2017-02-02 13:48 UTC, GowthamShanmugam commented
@r0h4n please review

2017-02-03 07:55 UTC, shtripat reviewed
LGTM.
Have you verified the import cluster flow post this once?

2017-02-03 08:05 UTC, r0h4n requested changes

2017-02-03 08:05 UTC, r0h4n commented on tendrl/ceph_integration/util.py
>  from pytz import utc
remove pytz import and remove pytz from requirements

2017-02-03 08:53 UTC, shtripat commented
@GowthamShanmugam where is commons PR for this?

2017-02-03 09:12 UTC, r0h4n commented
@shtripat  https://github.com/Tendrl/commons/pull/134

2017-02-08 05:37 UTC, GowthamShanmugam commented
@r0h4n changes done

2017-02-08 05:37 UTC, GowthamShanmugam commented
@shtripat still not verified with import cluster i will try

2017-02-08 06:54 UTC, GowthamShanmugam commented
@r0h4n all changes are done

2017-02-08 07:21 UTC, GowthamShanmugam commented
@shtripat i have verified with import cluster it is working fine.. for changes in common i updated with logging PR

2017-02-08 07:26 UTC, closed without merging