Corrected the reading logic for ceph version details
Tendrl/ceph_integration pull request #118
Opened 2017-02-16 13:49 UTC by shtripat

tendrl-bug-id: Tendrl/ceph-integration#112

Signed-off-by: Shubhendu <shtripat@redhat.com>

2017-02-17 08:03 UTC, mkudlej approved these changes
LGTM

2017-02-19 12:14 UTC, cybernth requested changes

2017-02-19 12:14 UTC, nthomas-redhat commented on tendrl/ceph_integration/objects/tendrl_context/__init__.py
> +            details = out.split()
Please add comment mentions the output of the ceph --version, which helps th ereview

2017-02-20 05:07 UTC, shtripat commented on tendrl/ceph_integration/objects/tendrl_context/__init__.py
> +            details = out.split()
Done. Will add some comments to explain

2017-02-20 07:10 UTC, shtripat commented
@Tendrl/tendrl-core plz review

2017-02-20 10:27 UTC, r0h4n approved these changes

2017-02-20 10:27 UTC, merged