Added in flight operation job update messages
Tendrl/ceph_integration pull request #120
Opened 2017-02-17 21:08 UTC by shtripat

tendrl-bug-id: Tendrl/ceph-integration#119

Signed-off-by: Shubhendu <shtripat@redhat.com>

2017-02-18 14:31 UTC, shtripat commented
Verified import cluster, create/delete/update pool, create/delete/resize rbd and create/delete ec-profiles flows.
A sample update pool job update status details look as below

```
{

    "action": "get",
    "node": {
        "key": "/clusters/d5f2afab-f188-45e8-9af6-8c587dca097f/_jobs/tendrl.ceph_integration.objects.Pool.flows.update_pool.UpdatePool_cc32f944-53ea-4f99-92ff-9d4765e6017e",
        "dir": true,
        "nodes": [
            {
                "key": "/clusters/d5f2afab-f188-45e8-9af6-8c587dca097f/_jobs/tendrl.ceph_integration.objects.Pool.flows.update_pool.UpdatePool_cc32f944-53ea-4f99-92ff-9d4765e6017e/00000000000000037716",
                "value": "{\"publisher\": \"ceph_integration\", \"timestamp\": \"2017-02-18T13:55:14.079261+00:00\", \"caller\": {\"function\": \"run\", \"line_no\": 86, \"filename\": \"__init__.py\"}, \"payload\": {\"message\": \"Updating min_size for pool-id 9 to 1\"}, \"priority\": \"info\", \"parent_id\": null, \"node_id\": \"9e3e5e2d-bfc6-430b-b958-2909f25f5424\", \"cluster_id\": \"d5f2afab-f188-45e8-9af6-8c587dca097f\", \"request_id\": \"clusters/d5f2afab-f188-45e8-9af6-8c587dca097f/_jobs/tendrl.ceph_integration.objects.Pool.flows.update_pool.UpdatePool_cc32f944-53ea-4f99-92ff-9d4765e6017e\", \"flow_id\": \"4ac41d8f-a0cf-420a-b2fe-18761e07f3b2\", \"message_id\": \"fae24f94-fef0-4dbd-b228-cfaf8a46750d\"}",
                "modifiedIndex": 37716,
                "createdIndex": 37716
            },
            {
                "key": "/clusters/d5f2afab-f188-45e8-9af6-8c587dca097f/_jobs/tendrl.ceph_integration.objects.Pool.flows.update_pool.UpdatePool_cc32f944-53ea-4f99-92ff-9d4765e6017e/00000000000000037719",
                "value": "{\"publisher\": \"ceph_integration\", \"timestamp\": \"2017-02-18T13:55:17.170875+00:00\", \"caller\": {\"function\": \"run\", \"line_no\": 123, \"filename\": \"__init__.py\"}, \"payload\": {\"message\": \"Pool 9 successfully updated\"}, \"priority\": \"info\", \"parent_id\": null, \"node_id\": \"9e3e5e2d-bfc6-430b-b958-2909f25f5424\", \"cluster_id\": \"d5f2afab-f188-45e8-9af6-8c587dca097f\", \"request_id\": \"clusters/d5f2afab-f188-45e8-9af6-8c587dca097f/_jobs/tendrl.ceph_integration.objects.Pool.flows.update_pool.UpdatePool_cc32f944-53ea-4f99-92ff-9d4765e6017e\", \"flow_id\": \"4ac41d8f-a0cf-420a-b2fe-18761e07f3b2\", \"message_id\": \"d68e1e41-20fe-4145-8bc8-3ec9addad46f\"}",
                "modifiedIndex": 37719,
                "createdIndex": 37719
            },
            {
                "key": "/clusters/d5f2afab-f188-45e8-9af6-8c587dca097f/_jobs/tendrl.ceph_integration.objects.Pool.flows.update_pool.UpdatePool_cc32f944-53ea-4f99-92ff-9d4765e6017e/00000000000000037713",
                "value": "{\"publisher\": \"ceph_integration\", \"timestamp\": \"2017-02-18T13:55:13.768988+00:00\", \"caller\": {\"function\": \"run\", \"line_no\": 24, \"filename\": \"__init__.py\"}, \"payload\": {\"message\": \"Starting updation flow for pool-id 9\"}, \"priority\": \"info\", \"parent_id\": null, \"node_id\": \"9e3e5e2d-bfc6-430b-b958-2909f25f5424\", \"cluster_id\": \"d5f2afab-f188-45e8-9af6-8c587dca097f\", \"request_id\": \"clusters/d5f2afab-f188-45e8-9af6-8c587dca097f/_jobs/tendrl.ceph_integration.objects.Pool.flows.update_pool.UpdatePool_cc32f944-53ea-4f99-92ff-9d4765e6017e\", \"flow_id\": \"4ac41d8f-a0cf-420a-b2fe-18761e07f3b2\", \"message_id\": \"6eb9d729-0bd5-4c6a-8962-b9fd9d85c0fc\"}",
                "modifiedIndex": 37713,
                "createdIndex": 37713
            },
            {
                "key": "/clusters/d5f2afab-f188-45e8-9af6-8c587dca097f/_jobs/tendrl.ceph_integration.objects.Pool.flows.update_pool.UpdatePool_cc32f944-53ea-4f99-92ff-9d4765e6017e/00000000000000037714",
                "value": "{\"publisher\": \"ceph_integration\", \"timestamp\": \"2017-02-18T13:55:14.073710+00:00\", \"caller\": {\"function\": \"run\", \"line_no\": 30, \"filename\": \"__init__.py\"}, \"payload\": {\"message\": \"Renaming pool-id 9 to darshan_update_pool\"}, \"priority\": \"info\", \"parent_id\": null, \"node_id\": \"9e3e5e2d-bfc6-430b-b958-2909f25f5424\", \"cluster_id\": \"d5f2afab-f188-45e8-9af6-8c587dca097f\", \"request_id\": \"clusters/d5f2afab-f188-45e8-9af6-8c587dca097f/_jobs/tendrl.ceph_integration.objects.Pool.flows.update_pool.UpdatePool_cc32f944-53ea-4f99-92ff-9d4765e6017e\", \"flow_id\": \"4ac41d8f-a0cf-420a-b2fe-18761e07f3b2\", \"message_id\": \"71122b1c-d283-4e80-8419-729e2a21185c\"}",
                "modifiedIndex": 37714,
                "createdIndex": 37714
            },
            {
                "key": "/clusters/d5f2afab-f188-45e8-9af6-8c587dca097f/_jobs/tendrl.ceph_integration.objects.Pool.flows.update_pool.UpdatePool_cc32f944-53ea-4f99-92ff-9d4765e6017e/00000000000000037715",
                "value": "{\"publisher\": \"ceph_integration\", \"timestamp\": \"2017-02-18T13:55:14.077416+00:00\", \"caller\": {\"function\": \"run\", \"line_no\": 70, \"filename\": \"__init__.py\"}, \"payload\": {\"message\": \"Updating size for pool-id 9 to 1\"}, \"priority\": \"info\", \"parent_id\": null, \"node_id\": \"9e3e5e2d-bfc6-430b-b958-2909f25f5424\", \"cluster_id\": \"d5f2afab-f188-45e8-9af6-8c587dca097f\", \"request_id\": \"clusters/d5f2afab-f188-45e8-9af6-8c587dca097f/_jobs/tendrl.ceph_integration.objects.Pool.flows.update_pool.UpdatePool_cc32f944-53ea-4f99-92ff-9d4765e6017e\", \"flow_id\": \"4ac41d8f-a0cf-420a-b2fe-18761e07f3b2\", \"message_id\": \"8c90d1e5-911a-4c9b-9d76-bfe0397edddc\"}",
                "modifiedIndex": 37715,
                "createdIndex": 37715
            }
        ],
        "modifiedIndex": 37713,
        "createdIndex": 37713
    }
}
```

2017-02-19 12:28 UTC, cybernth requested changes

2017-02-19 12:28 UTC, nthomas-redhat commented on etc/tendrl/ceph-integration/ceph-integration.conf.yaml.sample
> +logging_socket_path: /var/run/.tendrl.message.sock
I think we should keep it as /var/run/tendrl?

2017-02-19 12:28 UTC, nthomas-redhat commented on tendrl/ceph_integration/objects/ecprofile/atoms/create/__init__.py
> +
What if there is a failure? How it is handled and logged?
Comment applicable for all CRUD atoms

2017-02-19 12:28 UTC, nthomas-redhat commented on tendrl/ceph_integration/objects/pool/atoms/update/__init__.py
> +            Event(
I don't think we need to log messages on parameter by parameter basis. We can have a single message for the update and may be specify the params there

2017-02-20 05:49 UTC, shtripat commented on etc/tendrl/ceph-integration/ceph-integration.conf.yaml.sample
> +logging_socket_path: /var/run/.tendrl.message.sock
Done

2017-02-20 05:49 UTC, shtripat commented on tendrl/ceph_integration/objects/ecprofile/atoms/create/__init__.py
> +
In case of failures the job would be marked as failed and message would be logged. In the job there is no update here.

2017-02-20 05:49 UTC, shtripat commented on tendrl/ceph_integration/objects/pool/atoms/update/__init__.py
> +            Event(
Ok. will do that

2017-02-20 07:10 UTC, shtripat commented
@Tendrl/tendrl-core plz review

2017-02-20 10:46 UTC, r0h4n approved these changes

2017-02-20 10:47 UTC, merged