Added save_job method for push job object in etcd
Tendrl/ceph_integration pull request #139
Opened 2017-03-01 09:53 UTC by GowthamShanmugam

Signed-off-by: GowthamShanmugam <gshanmug@redhat.com>

2017-03-02 06:23 UTC, shtripat reviewed
LGTM

2017-03-06 14:41 UTC, r0h4n requested changes

2017-03-06 14:41 UTC, r0h4n commented on tendrl/ceph_integration/central_store/__init__.py
> +        tendrl_ns.etcd_orm.save(job)
Why is this required?

2017-03-06 14:54 UTC, GowthamShanmugam commented on tendrl/ceph_integration/central_store/__init__.py
> +        tendrl_ns.etcd_orm.save(job)
@r0h4n without this function ceph integration can't create or update jobs, job class is in common but it is stored  using save_job function in all components.

2017-03-06 15:05 UTC, GowthamShanmugam commented on tendrl/ceph_integration/central_store/__init__.py
> +        tendrl_ns.etcd_orm.save(job)
@r0h4n ah i forgot if i add in common then it is not required in all component..

2017-03-06 15:40 UTC, closed without merging