Removed yaml content from py files
Tendrl/ceph_integration pull request #165
Opened 2017-03-20 09:45 UTC by shtripat

tendrl-bug-id: Tendrl/ceph-integration#164
Signed-off-by: Shubhendu <shtripat@redhat.com>

2017-03-20 09:45 UTC, shtripat commented
@Tendrl/tendrl-core plz review

2017-03-20 21:48 UTC, r0h4n requested changes

2017-03-20 21:48 UTC, r0h4n commented on tendrl/ceph_integration/objects/definition/ceph.yaml
>  namespace.tendrl.ceph_integration:
This should be just "namespace.ceph", 

Final namespaces are eg: namespace.tendrl (commons), namespace.node_agent (node_agent), namespace.provisioning, namespace.integrations.ceph (in the node_agent and these will hold the ceph, gluster specific import/create flows/atoms/objects, which will be moved from commons), namespace.performance_monitoring, namespace.node_monitoring, namespace.alerting, namespace.ceph (ceph bridge), namespace.gluster (gluster bridge)

cc: @nthomas-redhat @anivargi @anmolbabu @GowthamShanmugam @nnDarshan @shtripat @anmolsachan  fyi

2017-03-21 05:08 UTC, shtripat commented on tendrl/ceph_integration/objects/definition/ceph.yaml
>  namespace.tendrl.ceph_integration:
Done

2017-03-21 08:40 UTC, r0h4n approved these changes

2017-03-21 08:45 UTC, merged