Set default value for provisioned key in rbd sync
Tendrl/ceph_integration pull request #214
Opened 2017-04-25 08:19 UTC by anmolsachan

Though the issue could not be replicated, for a safe condition we can set the provisioned value to be 0 if it is not found during sync.

tendrl_issue_id: https://github.com/Tendrl/ceph-integration/issues/172
Signed-off-by: anmolsachan asachan@redhat.com

2017-04-25 08:22 UTC, anmolsachan commented
@shtripat @GowthamShanmugam please review

2017-04-25 09:12 UTC, nthomas-redhat commented on tendrl/ceph_integration/sds_sync/__init__.py
> +                    provisioned=self._to_bytes(v.get("provisioned", 0)),
do you really want to set the value to 0 if not found?
I think v.get("provisioned") will solve this issue as if "provisioned" is not found , value will be set to 'None'

2017-04-25 09:13 UTC, cybernth requested changes
https://github.com/Tendrl/ceph-integration/pull/214/files#r113143238

2017-04-25 09:19 UTC, GowthamShanmugam commented on tendrl/ceph_integration/sds_sync/__init__.py
> +                    provisioned=self._to_bytes(v.get("provisioned", 0)),
@shtripat if provisioned field is not present then logic  written here also will give wrong value https://github.com/Tendrl/ceph-integration/blob/develop/tendrl/ceph_integration/sds_sync/__init__.py#L393

so setting 0 here is not solve the problem.

if provisioned filed is not there the du command will give used only, but as per loggic we written there will give wrong out put. so this solution will come there i feel.

2017-04-25 10:35 UTC, shtripat commented on tendrl/ceph_integration/sds_sync/__init__.py
> +                    provisioned=self._to_bytes(v.get("provisioned", 0)),
@GowthamShanmugam you can set `None` in sds_sync you can handle this `None` case properly. That would be the proper solution.

2017-04-25 18:39 UTC, anmolsachan commented on tendrl/ceph_integration/sds_sync/__init__.py
> +                    provisioned=self._to_bytes(v.get("provisioned", 0)),
I had given it 0 as here in definition, data type of provisioned shows int (https://github.com/Tendrl/ceph-integration/blob/develop/tendrl/ceph_integration/objects/definition/ceph.yaml#L271) . Should I put it as None ? @shtripat @nthomas-redhat @GowthamShanmugam

2017-04-26 04:40 UTC, shtripat commented on tendrl/ceph_integration/sds_sync/__init__.py
> +                    provisioned=self._to_bytes(v.get("provisioned", 0)),
@anmolsachan I feel just `v.get("provisioned")` you should try and it should work. The only thing in sds_sync take care properly for `None` case.

2017-04-26 09:28 UTC, nthomas-redhat commented on tendrl/ceph_integration/sds_sync/__init__.py
> +                    provisioned=self._to_bytes(v.get("provisioned", 0)),
There is another issue self._to_bytes('None') won't be right

2017-04-27 16:08 UTC, r0h4n approved these changes

2017-04-27 16:23 UTC, r0h4n approved these changes

2017-04-27 16:24 UTC, merged