Added logic to save monitor secret while start
Tendrl/ceph_integration pull request #237
Opened 2017-05-18 08:49 UTC by shtripat

This is required for the case of pure import of a cluster
created outside of tendrl. In such a case we should figure out
and persist the monitor secret to central store, so that
further additions of mons to the cluster can utilize the
same value.

tendrl-node-id: Tendrl/ceph-integration#236
Signed-off-by: Shubhendu <shtripat@redhat.com>

2017-05-18 09:29 UTC, r0h4n requested changes

2017-05-18 09:29 UTC, r0h4n commented on tendrl/ceph_integration/manager/__init__.py
> +    out, err, rc = cmd_utils.Command(
Why dont you put all this in the sds_sync thread?

2017-05-22 04:52 UTC, shtripat commented on tendrl/ceph_integration/manager/__init__.py
> +    out, err, rc = cmd_utils.Command(
The monitor key is something only once we need to save after import is successful. We dont need to keep this syncing again and again as this doesnt change once cluster is created.

If you are particular about sds_sync, may be we can add the code there with a check. If monitor doesnt exists already, we would sync else not.

Comments?

2017-06-01 09:42 UTC, shtripat commented
Verified

2017-06-06 06:56 UTC, r0h4n requested changes

2017-06-06 06:56 UTC, r0h4n commented on tendrl/ceph_integration/sds_sync/__init__.py
> +                pass
if the key exists, you should "return" instead of "pass" right?

2017-06-06 06:56 UTC, r0h4n commented on tendrl/ceph_integration/sds_sync/__init__.py
> +                        priority="warning",
this should be debug, the users dont need to know this

2017-06-06 06:56 UTC, r0h4n commented on tendrl/ceph_integration/sds_sync/__init__.py
> +                mon_sec = out.split('\n')[1].strip().split(' = ')[1].strip()
check if out is not None

2017-06-06 10:07 UTC, shtripat commented on tendrl/ceph_integration/sds_sync/__init__.py
> +                pass
We need to continue with other syncing stuff. If `_mon_key` just dont try to write it again.

2017-06-06 10:07 UTC, shtripat commented on tendrl/ceph_integration/sds_sync/__init__.py
> +                        priority="warning",
Done

2017-06-06 10:07 UTC, shtripat commented on tendrl/ceph_integration/sds_sync/__init__.py
> +                mon_sec = out.split('\n')[1].strip().split(' = ')[1].strip()
Done

2017-06-07 11:06 UTC, r0h4n requested changes

2017-06-07 11:06 UTC, r0h4n commented on tendrl/ceph_integration/sds_sync/__init__.py
> +                pass
ok then remove the "pass", if EtcdKeyNotFound is raised, you have handled it

2017-06-07 11:54 UTC, shtripat commented on tendrl/ceph_integration/sds_sync/__init__.py
> +                pass
Ok

2017-06-07 12:01 UTC, shtripat commented
Verified

2017-06-07 12:20 UTC, r0h4n approved these changes

2017-06-07 12:22 UTC, merged