Exposed sds sync interval as configuration
Tendrl/ceph_integration pull request #300
Opened 2017-06-19 08:17 UTC by shtripat

tendrl-bug-id: Tendrl/ceph-integration#299
Signed-off-by: Shubhendu <shtripat@redhat.com>

2017-06-19 11:25 UTC, shtripat commented
@Tendrl/tendrl-core plz review

2017-06-20 20:24 UTC, r0h4n requested changes

2017-06-20 20:24 UTC, r0h4n commented on tendrl/ceph_integration/sds_sync/__init__.py
> +            gevent.sleep(
This is not the only place that should use `sync_interval`

All the out of band object .save() with ttl should use ttl value by adding 10-15 seconds to `sync_interval`

2017-06-21 05:21 UTC, shtripat commented on tendrl/ceph_integration/sds_sync/__init__.py
> +            gevent.sleep(
Should I grep for ttl and whenever there is ttl being set for the entities, change it to `sync_interval + 15` ?

2017-06-21 09:22 UTC, shtripat commented on tendrl/ceph_integration/sds_sync/__init__.py
> +            gevent.sleep(
Currently there are no ttl references at the moment for entities in ceph-integration. When required we can use as `sync_interval + 15`

2017-06-22 10:15 UTC, r0h4n approved these changes

2017-06-22 10:15 UTC, merged