Added logic to sync cluster network details
Tendrl/ceph_integration pull request #311
Opened 2017-06-27 08:52 UTC by shtripat

tendrl-bug-id: Tendrl/ceph-integration#310
Signed-off-by: Shubhendu <shtripat@redhat.com>

2017-06-27 08:52 UTC, shtripat commented
Not yet verified

2017-06-27 11:15 UTC, r0h4n requested changes

2017-06-27 11:15 UTC, r0h4n commented on tendrl/ceph_integration/sds_sync/__init__.py
> +                NS.tendrl.objects.ClusterNetworkDetails(
ClusterNetworkDetails object should be `Cluster` 

check my comments here https://github.com/Tendrl/commons/pull/631

2017-06-27 13:51 UTC, shtripat commented on tendrl/ceph_integration/sds_sync/__init__.py
> +                NS.tendrl.objects.ClusterNetworkDetails(
Done

2017-06-28 10:31 UTC, r0h4n requested changes

2017-06-28 10:31 UTC, r0h4n commented on tendrl/ceph_integration/sds_sync/__init__.py
> +            NS.tendrl.objects.ClusterNetworkDetails(
use NS.tendrl.objects.Cluster

2017-06-28 10:31 UTC, r0h4n commented on tendrl/ceph_integration/sds_sync/__init__.py
> +            ).load()
use exists instead of load, then you dont need the try/except


update : IGNORE this comment

2017-06-28 10:37 UTC, r0h4n requested changes

2017-06-28 10:37 UTC, r0h4n commented on tendrl/ceph_integration/sds_sync/__init__.py
> +                pass
log appropriate msg and raise this exception instead of pass

2017-06-28 10:51 UTC, shtripat commented on tendrl/ceph_integration/sds_sync/__init__.py
> +            NS.tendrl.objects.ClusterNetworkDetails(
Ah my bad. It should be like done in gluster-integration. will change it.

2017-06-28 10:51 UTC, shtripat commented on tendrl/ceph_integration/sds_sync/__init__.py
> +                pass
Done

2017-06-28 11:18 UTC, r0h4n approved these changes

2017-06-28 11:21 UTC, merged