Create CHANGELOG.md
Tendrl/ceph_integration pull request #40
Opened 2016-11-16 19:24 UTC by nthomas-redhat

2016-11-16 19:31 UTC, r0h4n commented
the file type should be .rst

2016-11-16 19:32 UTC, r0h4n requested changes
file should be .rst and not .md

2016-11-17 07:35 UTC, nthomas-redhat commented
@r0h4n changed the format of the file

2016-11-17 14:57 UTC, shtripat commented on doc/source/CHANGELOG.md
> +[Unreleased]
Released now?

2016-11-17 14:57 UTC, shtripat commented on doc/source/CHANGELOG.md
> +[Unreleased]: <<github tag for this release>>
Released and add the correct tag name

2016-11-17 23:58 UTC, ktdreyer commented
Git commit logs still say `.md` rather than `.rst`. Want to amend and squash down?

In ceph-installer we've tried to follow the basic format that the [gitchangelog](https://pypi.python.org/pypi/gitchangelog) tool generates. it tends to speed things up when writing the text.

2016-12-06 17:40 UTC, closed without merging