Logged EtcdKeyNotFound exception from rpc.py
Tendrl/ceph_integration pull request #51
Opened 2016-12-07 10:13 UTC by GowthamShanmugam

Instead of the exception, EtcdKeyNotFound is logged successfully
tendrl-bug-id:Tendrl/ceph_integration#14

Signed-off-by: root <gshanmug@redhat.com>

2016-12-07 10:22 UTC, GowthamShanmugam commented
@r0h4n @shtripat @nnDarshan please review it

2016-12-07 10:30 UTC, nnDarshan reviewed
looks good to me

2016-12-08 04:28 UTC, shtripat commented on tendrl/ceph_integration/manager/rpc.py
> +                LOG.debug("Given key is not present in etcd . %s", ex)
I would prefer printing the key name in log message

2016-12-13 05:57 UTC, shtripat reviewed
Looks good to me

2016-12-13 13:22 UTC, r0h4n requested changes

2016-12-13 13:22 UTC, r0h4n commented on tendrl/ceph_integration/manager/rpc.py
> +            except etcd.EtcdKeyNotFound as ex:
Needs negative test case to assert if the etcd.EtcdKeyNotFound is caught

2016-12-13 16:01 UTC, GowthamShanmugam commented
@r0h4n please review it

2016-12-15 08:20 UTC, r0h4n requested changes
Actual PR looks good, but needinfo about the unrelated changes

2016-12-15 08:20 UTC, r0h4n commented on tendrl/ceph_integration/manager/rpc.py
> +    def __init__(self, manager, Etcdthread):
why is this change required here, is the same required in tendrl/gluster_integration/manager?

2016-12-15 09:03 UTC, GowthamShanmugam commented on tendrl/ceph_integration/manager/rpc.py
> +    def __init__(self, manager, Etcdthread):
EtcdRPC  have infinite loop. It will never stop. We have this check in other repos also.

2016-12-15 09:56 UTC, r0h4n approved these changes

2016-12-15 09:56 UTC, merged

2016-12-15 09:57 UTC, r0h4n commented on tendrl/ceph_integration/manager/rpc.py
> +    def __init__(self, manager, Etcdthread):
@GowthamShanmugam Please create issues on node-agent, gluster-integration, performance-monitoring, alerting

2016-12-15 09:58 UTC, GowthamShanmugam commented on tendrl/ceph_integration/manager/rpc.py
> +    def __init__(self, manager, Etcdthread):
ok i will create