Re factor ceph_integration module
Tendrl/ceph_integration pull request #63
Opened 2016-12-19 10:55 UTC by shtripat

2016-12-21 12:58 UTC, cybernth requested changes

2016-12-21 12:58 UTC, cybernth commented on tendrl/ceph_integration/flows/create_pool.py
> +        self.parameters.update(
Do we really need to pass this around? Instead directly call these from atoms.

2016-12-21 12:58 UTC, cybernth commented on tendrl/ceph_integration/flows/delete_pool.py
> +        self.parameters.update(
Same as above

2016-12-21 12:58 UTC, nthomas-redhat commented on tendrl/ceph_integration/manager/manager.py
> +        super(self).join()
Should it be super(CephIntegrationManager, self).join() ?

2016-12-21 12:58 UTC, nthomas-redhat commented on tendrl/ceph_integration/manager/manager.py
>                  utils.set_tendrl_context(cluster_id)
Does it create any issues during restart?

2016-12-21 12:58 UTC, nthomas-redhat commented on tendrl/ceph_integration/persistence/persister.py
> +class CephIntegrationFilePersister(FilePersister):
This can removed as it is not used as of now

2016-12-21 14:59 UTC, shtripat commented on tendrl/ceph_integration/flows/create_pool.py
> +        self.parameters.update(
Thats correct. we can import crud module and use the functions as is. Will change the logic accordingly.

2016-12-21 14:59 UTC, shtripat commented on tendrl/ceph_integration/flows/delete_pool.py
> +        self.parameters.update(
Done

2016-12-21 15:00 UTC, shtripat commented on tendrl/ceph_integration/manager/manager.py
> +        super(self).join()
Both are fine actually I feel

2016-12-21 15:01 UTC, shtripat commented on tendrl/ceph_integration/manager/manager.py
>                  utils.set_tendrl_context(cluster_id)
I am not sure at the moment and as we discussed earlier ideally we should be starting bridges as well as services and not child processes of the node agent. We can do this as part of a separate PR preferably as it applies to both gluster and ceph integration modules.

2016-12-21 15:02 UTC, shtripat commented on tendrl/ceph_integration/persistence/persister.py
> +class CephIntegrationFilePersister(FilePersister):
Done. Will remove this.

2017-01-03 12:15 UTC, nthomas-redhat commented on tendrl/ceph_integration/manager/manager.py
>                  utils.set_tendrl_context(cluster_id)
okay, do we have a git issue to track this?

2017-01-03 12:16 UTC, nthomas-redhat commented on tendrl/ceph_integration/manager/manager.py
> +        super(self).join()
okay

2017-01-03 12:49 UTC, shtripat commented on tendrl/ceph_integration/manager/manager.py
>                  utils.set_tendrl_context(cluster_id)
https://github.com/Tendrl/node_agent/issues/116 introduces starting of integration processes as services and not as command line process.

2017-01-05 09:49 UTC, r0h4n requested changes
Fix Travis unit tests, rest LGTM

2017-01-05 10:51 UTC, merged