Read cluster-id from a file instead of argument
Tendrl/ceph_integration pull request #69
Opened 2016-12-30 08:16 UTC by nnDarshan

Changed ceph_integration service to read cluster_id
from a file /var/lib/tendrl/ceph_cluster_id instead
of passing cluster_id to process as an argument.

tendrl-bug-id:Tendrl/ceph_integration#56
Signed-off-by: nnDarshan <darshan.n.2024@gmail.com>

2016-12-30 08:17 UTC, nnDarshan commented
@nthomas-redhat @shtripat @r0h4n Please review

2017-01-02 03:48 UTC, shtripat commented on tendrl/ceph_integration/manager/utils.py
> +TENDRL_CONTEXT = "/var/lib/tendrl/ceph_cluster_id"
Are we changing the path of the tendrl_context? and is /var/lib the correct path for this? I feel it should rather be /var/run/tendrl may be.

@Tendrl/tendrl-core comments?

2017-01-11 06:09 UTC, r0h4n requested changes

2017-01-11 06:09 UTC, r0h4n commented on tendrl/ceph_integration/manager/manager.py
> +        LOG.error("Could not find cluster_id")
could not find cluster_id where? please add path where you are looking for cluster_id or add some logging to get_tendrl_context()

2017-01-11 06:10 UTC, r0h4n commented on tendrl/ceph_integration/manager/utils.py
> +        return None
Add a log here saying no cluster id found at TENDRL_CONTEXT

2017-01-15 12:59 UTC, merged