Fix pep8 and UT issues
Tendrl/ceph_integration pull request #79
Opened 2017-01-16 07:19 UTC by nnDarshan

tendrl-bug-id: Tendrl/ceph_integration#62
Signed-off-by: nnDarshan <darshan.n.2024@gmail.com>

2017-01-16 07:20 UTC, nnDarshan commented
@r0h4n @nthomas-redhat @shtripat Please review

2017-01-16 07:58 UTC, cybernth requested changes

2017-01-16 07:58 UTC, nthomas-redhat commented on tendrl/ceph_integration/persistence/persister.py
> +    "/etc/tendrl/tendrl.conf"
Might not work. tendrl.conf is gone and you will have module specific files. Also this function expected to load yaml files

2017-01-16 10:55 UTC, r0h4n commented on tendrl/ceph_integration/persistence/persister.py
> +    "/etc/tendrl/tendrl.conf"
+1 @nnDarshan , this is a yaml loader, ensure you pass a yaml file path here

2017-01-16 10:55 UTC, r0h4n commented on tendrl/ceph_integration/persistence/persister.py
> +    "/etc/tendrl/tendrl.conf"
And replace gluster with ceph

2017-01-16 13:14 UTC, nnDarshan commented on tendrl/ceph_integration/persistence/persister.py
> +    "/etc/tendrl/tendrl.conf"
Done

2017-01-16 18:23 UTC, shtripat commented on tendrl/ceph_integration/manager/eventer.py
> +    "/etc/tendrl/ceph-integration/ceph-integration.conf.yaml"
We are following the naming as `ceph-integration.yaml`

2017-01-17 05:20 UTC, nnDarshan commented on tendrl/ceph_integration/manager/eventer.py
> +    "/etc/tendrl/ceph-integration/ceph-integration.conf.yaml"
Done

2017-01-17 05:31 UTC, shtripat reviewed
LGTM

2017-02-03 08:24 UTC, r0h4n commented
Please update this PR

2017-02-03 08:24 UTC, closed without merging